@startuml

class Client {}

package Middleware {
    Client -> ControllerBuilder

    ' Controller
    interface ControllerBuilder {
        setDataSource(String sourceID)
        setConnectionType(ConnType type)
        setMonitorType(ServiceType type)
        setFormula(Formula formula)
        setSpatialModel(SpatialModel model)
        run()
    }

    ' ServiceController
    class ConcreteControllerBuilder implements ControllerBuilder {
        run()
        ' implement the rest
    }

}


@enduml

